export const DEFAULT_STYLE = {
  geometry: { type: 'box' },
  baseScale: [1, 1, 1],
  scaleVariance: [0, 0, 0],
  sizeMultiplier: 1,
  sizeJitter: 0.25,
  colorBias: 0.5,
  colorVariance: 0.2,
  colorMode: 'mix',
  colorGradient: null,
  colorGradientSource: 'random',
  colorGradientPlayback: 'static',
  colorGradientSpeed: 0,
  opacityRange: [0.7, 1],
  emissiveMultiplier: 1.2,
  emissiveVariance: 0.15,
  roughness: 0.45,
  metalness: 0.2,
  alphaMode: 'OPAQUE',
  depthWrite: true,
  floatStrength: 0.2,
  floatFrequency: 2.0,
  verticalJitter: 0.2,
  radialJitter: 0.15,
  heightBias: 0,
  spreadMultiplier: 1,
  spinRates: [1.2, 0.9, 1.1],
  speedVariance: 0.25,
  driftStrength: 0,
  spiralHeight: 1.0,
  spiralTaper: 0.3,
  spiralRevolutions: 3,
  spiralAngularSpeed: 1,
  riseSpeed: 0.5,
  riseHeight: 3.2,
  explosionSpread: 2.0,
  explosionShrink: 0.85,
  pulseScaleBase: 0.55,
  pulseScaleRange: 0.75,
  systemRotationSpeed: 0.35,
  maxParticles: 160,
  keyframeSteps: 6,
  arcRadius: 1.5,
  arcStartAngle: Math.PI * 0.2,
  arcEndAngle: Math.PI * 0.8,
  arcThickness: 0.2,
  arcHeightOffset: 0,
  arcFlowSpeed: 1,
  arcFlowMode: 'continuous',
  arcLayers: null
}

export const PARTICLE_SHAPE_DEFINITIONS = [
  {
    id: 'style',
    name: 'Effect Default',
    icon: '🎯'
  },
  {
    id: 'cube',
    name: 'Block',
    icon: '🧊',
    geometry: { type: 'box' }
  },
  {
    id: 'sphere',
    name: 'Sphere',
    icon: '⚪',
    geometry: { type: 'sphere', widthSegments: 16, heightSegments: 12 }
  },
  {
    id: 'tetra',
    name: 'Tetrahedron',
    icon: '🔺',
    geometry: { type: 'tetrahedron' }
  },
  {
    id: 'octa',
    name: 'Octahedron',
    icon: '💠',
    geometry: { type: 'octahedron', detail: 0 }
  },
  {
    id: 'cylinder',
    name: 'Cylinder',
    icon: '🛢️',
    geometry: { type: 'cylinder', topRadius: 0.25, bottomRadius: 0.25, height: 1.2, radialSegments: 18, openEnded: false },
    styleOverrides: {
      baseScale: [0.7, 1.4, 0.7]
    }
  },
  {
    id: 'plane',
    name: 'Plane',
    icon: '⬛',
    geometry: { type: 'plane' },
    styleOverrides: {
      baseScale: [1.3, 0.1, 1.3],
      scaleVariance: [0.15, 0.05, 0.15]
    }
  }
]

export const PARTICLE_SHAPE_OPTIONS = PARTICLE_SHAPE_DEFINITIONS.map(shape => ({
  id: shape.id,
  name: shape.name,
  icon: shape.icon
}))

export const EFFECT_STYLES = {
  aura: {
    geometry: { type: 'icosahedron', detail: 1 },
    baseScale: [1, 1, 1],
    scaleVariance: [0.2, 0.2, 0.2],
    sizeMultiplier: 1.1,
    sizeJitter: 0.35,
    colorBias: 0.65,
    colorVariance: 0.3,
    opacityRange: [0.6, 0.95],
    emissiveMultiplier: 1.9,
    emissiveVariance: 0.25,
    roughness: 0.25,
    metalness: 0.12,
    alphaMode: 'BLEND',
    depthWrite: false,
    floatStrength: 0.4,
    floatFrequency: 2.6,
    verticalJitter: 0.45,
    radialJitter: 0.2,
    heightBias: 0.1,
    spreadMultiplier: 1.3,
    spinRates: [1.6, 1.1, 1.4],
    speedVariance: 0.18,
    driftStrength: 0.15,
    systemRotationSpeed: 0.42
  },
  fireball: {
    geometry: { type: 'sphere', widthSegments: 16, heightSegments: 12 },
    baseScale: [1, 1, 1],
    scaleVariance: [0.1, 0.1, 0.1],
    sizeMultiplier: 1.35,
    sizeJitter: 0.28,
    colorBias: 0.35,
    colorVariance: 0.22,
    opacityRange: [0.75, 1],
    emissiveMultiplier: 2.6,
    emissiveVariance: 0.2,
    roughness: 0.35,
    metalness: 0.18,
    floatStrength: 0.18,
    floatFrequency: 3.2,
    verticalJitter: 0.25,
    radialJitter: 0.18,
    spreadMultiplier: 0.9,
    spinRates: [2.1, 1.4, 1.6],
    speedVariance: 0.22,
    explosionSpread: 2.8,
    explosionShrink: 0.9,
    maxParticles: 120
  },
  ice: {
    geometry: { type: 'octahedron', detail: 1 },
    baseScale: [1, 1.2, 1],
    scaleVariance: [0.15, 0.2, 0.15],
    sizeMultiplier: 1.05,
    sizeJitter: 0.2,
    colorBias: 0.7,
    colorVariance: 0.18,
    opacityRange: [0.65, 0.9],
    emissiveMultiplier: 1.4,
    emissiveVariance: 0.15,
    roughness: 0.55,
    metalness: 0.05,
    alphaMode: 'BLEND',
    depthWrite: false,
    floatStrength: 0.28,
    floatFrequency: 2.1,
    verticalJitter: 0.35,
    radialJitter: 0.12,
    heightBias: 0.2,
    spreadMultiplier: 1.15,
    spinRates: [1.1, 0.8, 1.3],
    speedVariance: 0.16,
    driftStrength: 0.12
  },
  'ground-smash': {
    geometry: { type: 'box' },
    baseScale: [1.4, 0.6, 1.4],
    scaleVariance: [0.2, 0.15, 0.2],
    sizeMultiplier: 1.55,
    sizeJitter: 0.22,
    colorBias: 0.45,
    colorVariance: 0.18,
    opacityRange: [0.85, 1],
    emissiveMultiplier: 1.0,
    emissiveVariance: 0.1,
    roughness: 0.85,
    metalness: 0.06,
    floatStrength: 0.08,
    floatFrequency: 1.5,
    verticalJitter: 0.25,
    radialJitter: 0.35,
    heightBias: -0.25,
    spreadMultiplier: 1.4,
    spinRates: [0.6, 1.3, 0.5],
    speedVariance: 0.12,
    explosionSpread: 1.9,
    explosionShrink: 0.7,
    riseHeight: 2.2,
    maxParticles: 90
  },
  tornado: {
    customEmitter: 'vortex',
    geometry: { type: 'cylinder', topRadius: 0.08, bottomRadius: 0.4, height: 1.4, radialSegments: 20, openEnded: true },
    baseScale: [0.35, 2.8, 0.35],
    scaleVariance: [0.25, 0.65, 0.25],
    sizeMultiplier: 1.0,
    sizeJitter: 0.28,
    colorBias: 0.52,
    colorVariance: 0.22,
    opacityRange: [0.45, 0.85],
    emissiveMultiplier: 1.6,
    emissiveVariance: 0.22,
    roughness: 0.48,
    metalness: 0.1,
    alphaMode: 'BLEND',
    depthWrite: false,
    floatStrength: 0.14,
    floatFrequency: 2.8,
    verticalJitter: 0.4,
    radialJitter: 0.08,
    spreadMultiplier: 1.25,
    spinRates: [0.9, 2.4, 1],
    speedVariance: 0.24,
    spiralHeight: 3.2,
    spiralTaper: 0.55,
    spiralRevolutions: 5.5,
    spiralAngularSpeed: 1.1,
    driftStrength: 0.12,
    vortexHeight: 3.6,
    vortexBaseRadius: 1.45,
    vortexTipRadius: 0.18,
    vortexRadiusFalloff: 1.4,
    vortexLayers: 20,
    vortexLayerDrift: 0.85,
    vortexJitter: 0.08,
    vortexVerticalJitter: 0.05,
    vortexSway: 0.1,
    vortexSwaySpeed: 1.4,
    vortexSwayRadius: 0.06,
    systemRotationSpeed: 0.48,
    maxParticles: 150
  },
  sparkles: {
    geometry: { type: 'tetrahedron' },
    baseScale: [1, 1, 1],
    scaleVariance: [0.35, 0.35, 0.35],
    sizeMultiplier: 0.95,
    sizeJitter: 0.5,
    colorBias: 0.5,
    colorVariance: 0.4,
    opacityRange: [0.35, 0.8],
    emissiveMultiplier: 3,
    emissiveVariance: 0.35,
    roughness: 0.15,
    metalness: 0.15,
    alphaMode: 'BLEND',
    depthWrite: false,
    floatStrength: 0.5,
    floatFrequency: 4.2,
    verticalJitter: 0.4,
    radialJitter: 0.15,
    spreadMultiplier: 1,
    spinRates: [3.1, 2.8, 2.2],
    speedVariance: 0.32,
    pulseScaleBase: 0.45,
    pulseScaleRange: 1.0,
    driftStrength: 0.1,
    maxParticles: 150,
    keyframeSteps: 8
  },
  smoke: {
    geometry: { type: 'sphere', widthSegments: 14, heightSegments: 12 },
    baseScale: [0.85, 1.1, 0.85],
    scaleVariance: [0.3, 0.45, 0.3],
    sizeMultiplier: 1.3,
    sizeJitter: 0.4,
    colorBias: 0.55,
    colorVariance: 0.2,
    opacityRange: [0.28, 0.6],
    emissiveMultiplier: 0.4,
    emissiveVariance: 0.12,
    roughness: 0.95,
    metalness: 0.02,
    alphaMode: 'BLEND',
    depthWrite: false,
    floatStrength: 0.12,
    floatFrequency: 1.6,
    verticalJitter: 0.35,
    radialJitter: 0.1,
    heightBias: 0.05,
    spreadMultiplier: 0.85,
    spinRates: [0.25, 0.4, 0.3],
    speedVariance: 0.18,
    driftStrength: 0.35,
    riseSpeed: 0.42,
    riseHeight: 3,
    maxParticles: 140,
    clusterCount: 6,
    clusterRadius: 0.35,
    clusterScatter: 0.28,
    clusterVerticalScatter: 0.6,
    clusterHeightRange: 0.45,
    clusterBaseHeight: -0.1,
    clusterDelayRange: 0.55,
    clusterRiseJitter: 0.25,
    riseScaleStart: 0.35,
    riseScaleEnd: 1.35
  },
  'energy-beam': {
    geometry: { type: 'cylinder', topRadius: 0.08, bottomRadius: 0.08, height: 1.4, radialSegments: 12, openEnded: true },
    baseScale: [0.22, 2.4, 0.22],
    scaleVariance: [0.08, 0.12, 0.08],
    sizeMultiplier: 1.05,
    sizeJitter: 0.15,
    colorBias: 0.35,
    colorVariance: 0.18,
    opacityRange: [0.55, 0.95],
    emissiveMultiplier: 4.2,
    emissiveVariance: 0.28,
    roughness: 0.1,
    metalness: 0.3,
    alphaMode: 'BLEND',
    depthWrite: false,
    floatStrength: 0.08,
    floatFrequency: 4,
    verticalJitter: 0.05,
    radialJitter: 0.06,
    heightBias: 0,
    spreadMultiplier: 0.4,
    spinRates: [1.2, 2.1, 1.2],
    speedVariance: 0.12,
    driftStrength: 0.02,
    riseSpeed: 0.65,
    riseHeight: 5.2,
    riseScaleStart: 0.35,
    riseScaleEnd: 1.6,
    systemRotationSpeed: 0.2,
    maxParticles: 180,
    beamStrandCount: 18,
    beamRadius: 0.16,
    beamNoise: 0.05,
    beamVerticalJitter: 0.15,
    beamHeight: 5,
    beamHeightJitter: 0.6,
    beamDelayRange: 0.9,
    beamDelayJitter: 0.15,
    beamBaseHeight: -0.2
  },
  rainbow: {
    customEmitter: 'rainbowArc',
    geometry: { type: 'plane' },
    baseScale: [0.6, 0.6, 0.6],
    scaleVariance: [0.12, 0.08, 0.12],
    sizeMultiplier: 0.9,
    sizeJitter: 0.12,
    colorMode: 'gradient',
    colorGradient: [
      { stop: 0, color: '#d71c1c' },
      { stop: 0.16, color: '#ffdf00' },
      { stop: 0.33, color: '#08ff00' },
      { stop: 0.5, color: '#00ffff' },
      { stop: 0.67, color: '#0000ff' },
      { stop: 0.83, color: '#ff00ff' },
      { stop: 1, color: '#e21111' }
    ],
    colorGradientSource: 'layer',
    colorGradientPlayback: 'static',
    colorGradientSpeed: 0,
    opacityRange: [0.55, 0.95],
    emissiveMultiplier: 1.6,
    emissiveVariance: 0.2,
    roughness: 0.2,
    metalness: 0.05,
    alphaMode: 'BLEND',
    depthWrite: false,
    floatStrength: 0.05,
    floatFrequency: 1.5,
    radialJitter: 0.01,
    verticalJitter: 0.02,
    spreadMultiplier: 1,
    spinRates: [0.45, 0.9, 0.45],
    speedVariance: 0.08,
    driftStrength: 0.05,
    pulseScaleBase: 0.7,
    pulseScaleRange: 0.3,
    systemRotationSpeed: 0.5,
    maxParticles: 220,
    keyframeSteps: 8,
    arcRadius: 3,
    arcStartAngle: Math.PI * 0.1,
    arcEndAngle: Math.PI * 0.9,
    arcThickness: 0.12,
    arcHeightOffset: 0,
    arcFlowSpeed: 0.75,
    arcFlowMode: 'continuous',
    arcLayers: null
  }
}

export const EFFECT_PRESETS = {
  aura: {
    particleCount: 90,
    particleSize: 0.18,
    particleSpeed: 0.8,
    spread: 1.4,
    primaryColor: '#7f75ff',
    secondaryColor: '#a7f7ff',
    emissionShape: 'sphere',
    animationType: 'orbit',
    glowIntensity: 1,
    lifetime: 3,
    particleShape: 'style'
  },
  fireball: {
    particleCount: 70,
    particleSize: 0.24,
    particleSpeed: 1.9,
    spread: 0.9,
    primaryColor: '#ff4b1f',
    secondaryColor: '#ffb347',
    emissionShape: 'sphere',
    animationType: 'explode',
    glowIntensity: 1,
    lifetime: 1.6,
    particleShape: 'style'
  },
  ice: {
    particleCount: 65,
    particleSize: 0.17,
    particleSpeed: 1,
    spread: 1.2,
    primaryColor: '#66d4ff',
    secondaryColor: '#f3fbff',
    emissionShape: 'cone',
    animationType: 'rise',
    glowIntensity: 1,
    lifetime: 2.8,
    particleShape: 'style'
  },
  'ground-smash': {
    particleCount: 50,
    particleSize: 0.3,
    particleSpeed: 1.3,
    spread: 1.6,
    primaryColor: '#8b5a2b',
    secondaryColor: '#f2d3a2',
    emissionShape: 'box',
    animationType: 'explode',
    glowIntensity: 1,
    lifetime: 1.4,
    particleShape: 'style'
  },
  tornado: {
    particleCount: 140,
    particleSize: 0.17,
    particleSpeed: 1.9,
    spread: 1.5,
    primaryColor: '#7dd8ff',
    secondaryColor: '#e0f7ff',
    emissionShape: 'cone',
    animationType: 'spiral',
    glowIntensity: 1,
    lifetime: 3.8,
    particleShape: 'style'
  },
  sparkles: {
    particleCount: 120,
    particleSize: 0.15,
    particleSpeed: 2,
    spread: 1,
    primaryColor: '#fff8c6',
    secondaryColor: '#ffe4f6',
    emissionShape: 'ring',
    animationType: 'pulse',
    glowIntensity: 1,
    lifetime: 2.2,
    particleShape: 'style'
  },
  smoke: {
    particleCount: 85,
    particleSize: 0.32,
    particleSpeed: 0.7,
    spread: 1.7,
    primaryColor: '#6b6b6b',
    secondaryColor: '#a8a8a8',
    emissionShape: 'sphere',
    animationType: 'rise',
    glowIntensity: 1,
    lifetime: 3.6,
    particleShape: 'style'
  },
  'energy-beam': {
    particleCount: 220,
    particleSize: 0.16,
    particleSpeed: 1.1,
    spread: 0.28,
    primaryColor: '#45f6ff',
    secondaryColor: '#b6f3ff',
    emissionShape: 'disc',
    animationType: 'rise',
    glowIntensity: 1.3,
    lifetime: 2.6,
    particleShape: 'style',
    motionDirectionMode: 'custom',
    motionDirection: { x: 0, y: 1, z: 0 },
    motionAcceleration: { x: 0, y: 0.35, z: 0 }
  },
  rainbow: {
    particleCount: 200,
    particleSize: 0.15,
    particleSpeed: 0,
    spread: 2.6,
    primaryColor: '#d71c1c',
    secondaryColor: '#e21111',
    emissionShape: 'disc',
    animationType: 'orbit',
    glowIntensity: 1.15,
    lifetime: 1.8,
    particleShape: 'style',
    emissionSurfaceOnly: true,
    emissionOffset: { x: 0, y: 0.05, z: 0 },
    motionDirectionMode: 'outwards',
    motionAcceleration: { x: 0, y: 0.4, z: 0 },
    useArcEmitter: true,
    arcRadius: 3,
    arcStartAngle: Math.PI * 0.05,
    arcEndAngle: Math.PI * 0.95,
    arcThickness: 0.18,
    arcHeightOffset: 0,
    arcFlowSpeed: 0.75,
    arcFlowMode: 'continuous',
    colorGradient: [
      { stop: 0, color: '#d71c1c' },
      { stop: 0.16, color: '#ffdf00' },
      { stop: 0.33, color: '#08ff00' },
      { stop: 0.5, color: '#00ffff' },
      { stop: 0.67, color: '#0000ff' },
      { stop: 0.83, color: '#ff00ff' },
      { stop: 1, color: '#e21111' }
    ],
    colorGradientSource: 'angle',
    colorGradientPlayback: 'static'
  }
}

export const getParticleShapeDefinition = (shapeId) => {
  if (!shapeId || shapeId === 'style') return null
  return PARTICLE_SHAPE_DEFINITIONS.find(shape => shape.id === shapeId) || null
}
